#ifndef GPIO_CORE_ISR_H
#define GPIO_CORE_ISR_H

#include "GPIO_CORE.h"

extern GPIO_CORE *GPIO_PTR[GPIO_CORE_PIN_COUNT];

void IRAM_ATTR GPIO_CORE_ISR_D0();
void IRAM_ATTR GPIO_CORE_ISR_D1();
void IRAM_ATTR GPIO_CORE_ISR_D2();
void IRAM_ATTR GPIO_CORE_ISR_D3();
void IRAM_ATTR GPIO_CORE_ISR_D4();
void IRAM_ATTR GPIO_CORE_ISR_D5();
void IRAM_ATTR GPIO_CORE_ISR_D6();
void IRAM_ATTR GPIO_CORE_ISR_D7();
void IRAM_ATTR GPIO_CORE_ISR_D8();
void IRAM_ATTR GPIO_CORE_ISR_D9();
void IRAM_ATTR GPIO_CORE_ISR_D10();
void IRAM_ATTR GPIO_CORE_ISR_D11();
void IRAM_ATTR GPIO_CORE_ISR_D12();
void IRAM_ATTR GPIO_CORE_ISR_D13();
void IRAM_ATTR GPIO_CORE_ISR_D14();
void IRAM_ATTR GPIO_CORE_ISR_D15();
void IRAM_ATTR GPIO_CORE_ISR_D16();
void IRAM_ATTR GPIO_CORE_ISR_D17();
void IRAM_ATTR GPIO_CORE_ISR_D18();
void IRAM_ATTR GPIO_CORE_ISR_D19();
void IRAM_ATTR GPIO_CORE_ISR_D20();
void IRAM_ATTR GPIO_CORE_ISR_D21();
void IRAM_ATTR GPIO_CORE_ISR_D22();
void IRAM_ATTR GPIO_CORE_ISR_D23();
void IRAM_ATTR GPIO_CORE_ISR_D24();
void IRAM_ATTR GPIO_CORE_ISR_D25();
void IRAM_ATTR GPIO_CORE_ISR_D26();
void IRAM_ATTR GPIO_CORE_ISR_D27();
void IRAM_ATTR GPIO_CORE_ISR_D28();
void IRAM_ATTR GPIO_CORE_ISR_D29();
void IRAM_ATTR GPIO_CORE_ISR_D30();
void IRAM_ATTR GPIO_CORE_ISR_D31();
void IRAM_ATTR GPIO_CORE_ISR_D32();
void IRAM_ATTR GPIO_CORE_ISR_D33();
void IRAM_ATTR GPIO_CORE_ISR_D34();
void IRAM_ATTR GPIO_CORE_ISR_D35();
void IRAM_ATTR GPIO_CORE_ISR_D36();
void IRAM_ATTR GPIO_CORE_ISR_D37();
void IRAM_ATTR GPIO_CORE_ISR_D38();
void IRAM_ATTR GPIO_CORE_ISR_D39();

#endif