#ifdef ESP32 

#include "interrupt.h"

void IRAM_ATTR GPIO_CORE_ISR_D0() { GPIO_PTR[0]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D1() { GPIO_PTR[1]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D2() { GPIO_PTR[2]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D3() { GPIO_PTR[3]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D4() { GPIO_PTR[4]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D5() { GPIO_PTR[5]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D6() { GPIO_PTR[6]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D7() { GPIO_PTR[7]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D8() { GPIO_PTR[8]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D9() { GPIO_PTR[9]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D10() { GPIO_PTR[10]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D11() { GPIO_PTR[11]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D12() { GPIO_PTR[12]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D13() { GPIO_PTR[13]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D14() { GPIO_PTR[14]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D15() { GPIO_PTR[15]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D16() { GPIO_PTR[16]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D17() { GPIO_PTR[17]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D18() { GPIO_PTR[18]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D19() { GPIO_PTR[19]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D20() { GPIO_PTR[20]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D21() { GPIO_PTR[21]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D22() { GPIO_PTR[22]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D23() { GPIO_PTR[23]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D24() { GPIO_PTR[24]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D25() { GPIO_PTR[25]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D26() { GPIO_PTR[26]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D27() { GPIO_PTR[27]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D28() { GPIO_PTR[28]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D29() { GPIO_PTR[29]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D30() { GPIO_PTR[30]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D31() { GPIO_PTR[31]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D32() { GPIO_PTR[32]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D33() { GPIO_PTR[33]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D34() { GPIO_PTR[34]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D35() { GPIO_PTR[35]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D36() { GPIO_PTR[36]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D37() { GPIO_PTR[37]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D38() { GPIO_PTR[38]->HANDLE_ISR();}
void IRAM_ATTR GPIO_CORE_ISR_D39() { GPIO_PTR[39]->HANDLE_ISR();}

void IRAM_ATTR (*GPIO_CORE_ISR[GPIO_CORE_ISR_PIN_COUNT])() = {
	GPIO_CORE_ISR_D0,
	GPIO_CORE_ISR_D1,
	GPIO_CORE_ISR_D2,
	GPIO_CORE_ISR_D3,
	GPIO_CORE_ISR_D4,
	GPIO_CORE_ISR_D5,
	GPIO_CORE_ISR_D6,
	GPIO_CORE_ISR_D7,
	GPIO_CORE_ISR_D8,
	GPIO_CORE_ISR_D9,
	GPIO_CORE_ISR_D10,
	GPIO_CORE_ISR_D11,
	GPIO_CORE_ISR_D12,
	GPIO_CORE_ISR_D13,
	GPIO_CORE_ISR_D14,
	GPIO_CORE_ISR_D15,
	GPIO_CORE_ISR_D16,
	GPIO_CORE_ISR_D17,
	GPIO_CORE_ISR_D18,
	GPIO_CORE_ISR_D19,
	GPIO_CORE_ISR_D20,
	GPIO_CORE_ISR_D21,
	GPIO_CORE_ISR_D22,
	GPIO_CORE_ISR_D23,
	GPIO_CORE_ISR_D24,
	GPIO_CORE_ISR_D25,
	GPIO_CORE_ISR_D26,
	GPIO_CORE_ISR_D27,
	GPIO_CORE_ISR_D28,
	GPIO_CORE_ISR_D29,
	GPIO_CORE_ISR_D30,
	GPIO_CORE_ISR_D31,
	GPIO_CORE_ISR_D32,
	GPIO_CORE_ISR_D33,
	GPIO_CORE_ISR_D34,
	GPIO_CORE_ISR_D35,
	GPIO_CORE_ISR_D36,
	GPIO_CORE_ISR_D37,
	GPIO_CORE_ISR_D38,
	GPIO_CORE_ISR_D39
};

#endif