#ifndef GPIO_CORE_ISR_H
#define GPIO_CORE_ISR_H

#include "GPIO_CORE.h"

extern GPIO_CORE *GPIO_PTR[GPIO_CORE_PIN_COUNT];

void ICACHE_RAM_ATTR GPIO_CORE_ISR_D0();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D1();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D2();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D3();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D4();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D5();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D6();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D7();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D8();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D9();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D10();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D11();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D12();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D13();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D14();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D15();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D16();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D17();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D18();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D19();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D20();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D21();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D22();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D23();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D24();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D25();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D26();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D27();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D28();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D29();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D30();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D31();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D32();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D33();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D34();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D35();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D36();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D37();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D38();
void ICACHE_RAM_ATTR GPIO_CORE_ISR_D39();

#endif